packageName: dev.horologia.mobile.api
apiPackage: dev.horologia.mobile.api.apis
modelPackage: dev.horologia.mobile.api.models
artifactId: horologia-api-generated
library: multiplatform
dateLibrary: kotlinx-datetime
sourceFolder: src/commonMain/kotlin
enumPropertyNaming: original
useCoroutines: true
hideGenerationTimestamp: true
sortModelPropertiesByRequiredFlag: true
sortParamsByRequiredFlag: true
omitGradleWrapper: true
omitGradlePluginVersions: true
generateApiTests: false
generateModelTests: false
generateApiDocumentation: false
generateModelDocumentation: false
