/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth_listTokens"];
        put?: never;
        post: operations["Auth_createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Auth_deleteToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Spaces_list"];
        put?: never;
        post: operations["Spaces_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Spaces_read"];
        put?: never;
        post?: never;
        delete: operations["Spaces_delete"];
        options?: never;
        head?: never;
        patch: operations["Spaces_update"];
        trace?: never;
    };
    "/spaces/{spaceSlug}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceActivity_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceMembers_list"];
        put?: never;
        post: operations["SpaceMembers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SpaceMembers_delete"];
        options?: never;
        head?: never;
        patch: operations["SpaceMembers_update"];
        trace?: never;
    };
    "/spaces/{spaceSlug}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceTags_list"];
        put?: never;
        post: operations["SpaceTags_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/tags/{tagName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SpaceTags_delete"];
        options?: never;
        head?: never;
        patch: operations["SpaceTags_update"];
        trace?: never;
    };
    "/spaces/{spaceSlug}/task-effort-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceTaskEffortLevels_list"];
        put: operations["SpaceTaskEffortLevels_replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/task-priority-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceTaskPriorityLevels_list"];
        put: operations["SpaceTaskPriorityLevels_replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/task-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceTaskStatuses_list"];
        put: operations["SpaceTaskStatuses_replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceTasks_list"];
        put?: never;
        post: operations["SpaceTasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceTasks_read"];
        put?: never;
        post?: never;
        delete: operations["SpaceTasks_delete"];
        options?: never;
        head?: never;
        patch: operations["SpaceTasks_update"];
        trace?: never;
    };
    "/spaces/{spaceSlug}/tasks/{taskId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaceTaskActivity_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/tasks/{taskId}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SpaceTaskRelations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceSlug}/tasks/{taskId}/relations/{kind}/{relatedTaskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SpaceTaskRelations_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserActivity_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ActivityAction: "created" | "updated" | "deleted";
        ActivityDetail: {
            field: string;
            from: string | null;
            to: string | null;
        };
        /** @enum {string} */
        ActivityEntityType: "task" | "space" | "member" | "tag" | "status" | "effort_level" | "priority_level" | "relation";
        ActivityLogEntry: {
            id: string;
            spaceSlug: string;
            actorId: string | null;
            tokenId: string | null;
            tokenName: string | null;
            entityType: components["schemas"]["ActivityEntityType"];
            entityId: string;
            action: components["schemas"]["ActivityAction"];
            details: components["schemas"]["ActivityDetail"][];
            /** Format: date-time */
            createdAt: string;
        };
        ActivityLogPage: {
            items: components["schemas"]["ActivityLogEntry"][];
            nextCursor: string | null;
        };
        ApiError: {
            code: string;
            message: string;
        };
        AuthToken: {
            id: string;
            name: string;
            kind: components["schemas"]["AuthTokenKind"];
            /** Format: date-time */
            createdAt: string;
        };
        AuthTokenCreate: {
            name: string;
        };
        AuthTokenCreateResponse: {
            token: string;
            authToken: components["schemas"]["AuthToken"];
        };
        /** @enum {string} */
        AuthTokenKind: "session" | "api";
        AuthTokenPage: {
            items: components["schemas"]["AuthToken"][];
            nextCursor: string | null;
        };
        Space: {
            slug: string;
            name: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SpaceCreate: {
            slug: string;
            name: string;
            description?: string;
        };
        SpaceList: {
            items: components["schemas"]["Space"][];
        };
        SpaceMember: {
            userId: string;
            userName: string;
            userEmail: string;
            role: components["schemas"]["SpaceRole"];
            /** Format: date-time */
            createdAt: string;
        };
        SpaceMemberCreate: {
            userId: string;
            role: components["schemas"]["SpaceRole"];
        };
        SpaceMemberList: {
            items: components["schemas"]["SpaceMember"][];
        };
        SpaceMemberUpdate: {
            role: components["schemas"]["SpaceRole"];
        };
        /** @enum {string} */
        SpaceRole: "admin" | "member" | "viewer";
        SpaceUpdate: {
            slug?: string;
            name?: string;
            description?: string;
        };
        Tag: {
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        TagCreate: {
            name: string;
        };
        TagPage: {
            items: components["schemas"]["Tag"][];
            nextCursor: string | null;
        };
        TagUpdate: {
            name: string;
        };
        Task: {
            id: string;
            title: string;
            description: string;
            status: string;
            effort: string | null;
            priority: string | null;
            recurrenceType: components["schemas"]["TaskRecurrenceType"];
            recurrenceRule: string | null;
            lastCompletedAt: string | null;
            assigneeIds: string[];
            rotationPool: string[];
            tags: string[];
            relations: components["schemas"]["TaskRelation"][];
            due: components["schemas"]["TaskDue"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TaskCreate: {
            title: string;
            description?: string;
            status?: string;
            effort?: string;
            priority?: string;
            recurrenceType?: components["schemas"]["TaskRecurrenceType"];
            recurrenceRule?: string;
            assigneeIds?: string[];
            rotationPool?: string[];
            tags?: string[];
            due?: components["schemas"]["TaskDue"] | null;
        };
        TaskDue: {
            /** Format: date */
            at: string;
            timezone: string;
        };
        TaskEffortLevel: {
            name: string;
            /** Format: int64 */
            position: number;
        };
        TaskEffortLevelInput: {
            name: string;
        };
        TaskEffortLevelList: {
            items: components["schemas"]["TaskEffortLevel"][];
        };
        TaskEffortLevelReplace: {
            items: components["schemas"]["TaskEffortLevelInput"][];
        };
        TaskPage: {
            items: components["schemas"]["Task"][];
            nextCursor: string | null;
        };
        TaskPriorityLevel: {
            name: string;
            /** Format: int64 */
            position: number;
        };
        TaskPriorityLevelInput: {
            name: string;
        };
        TaskPriorityLevelList: {
            items: components["schemas"]["TaskPriorityLevel"][];
        };
        TaskPriorityLevelReplace: {
            items: components["schemas"]["TaskPriorityLevelInput"][];
        };
        /** @enum {string} */
        TaskRecurrenceType: "one_off" | "completion_based" | "fixed_non_accumulating" | "fixed_accumulating" | "on_dependency";
        TaskRelation: {
            kind: components["schemas"]["TaskRelationKind"];
            taskId: string;
            /** Format: date-time */
            createdAt: string;
        };
        TaskRelationCreate: {
            kind: components["schemas"]["TaskRelationKind"];
            taskId: string;
        };
        /** @enum {string} */
        TaskRelationKind: "parent_of" | "child_of" | "blocks" | "blocked_by" | "relates_to" | "duplicates" | "triggers" | "triggered_by" | "spawns" | "spawned_by";
        TaskStatus: {
            name: string;
            category: components["schemas"]["TaskStatusCategory"];
            /** Format: int64 */
            position: number;
        };
        /** @enum {string} */
        TaskStatusCategory: "initial" | "intermediate" | "completion";
        TaskStatusInput: {
            name: string;
            category: components["schemas"]["TaskStatusCategory"];
        };
        TaskStatusList: {
            items: components["schemas"]["TaskStatus"][];
        };
        TaskStatusReplace: {
            items: components["schemas"]["TaskStatusInput"][];
        };
        TaskUpdate: {
            title?: string;
            description?: string;
            status?: string;
            effort?: string | null;
            priority?: string | null;
            recurrenceType?: components["schemas"]["TaskRecurrenceType"];
            recurrenceRule?: string | null;
            assigneeIds?: string[];
            rotationPool?: string[];
            tags?: string[];
            due?: components["schemas"]["TaskDue"] | null;
        };
        User: {
            id: string;
            email: string;
            name: string;
            isOwner: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: {
        "PageParams.cursor": string;
        "PageParams.limit": number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Auth_listTokens: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["PageParams.cursor"];
                limit?: components["parameters"]["PageParams.limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenPage"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Auth_createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthTokenCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenCreateResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Auth_deleteToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Spaces_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceList"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Spaces_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Space"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Spaces_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Space"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Spaces_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Spaces_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Space"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceActivity_list: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["PageParams.cursor"];
                limit?: components["parameters"]["PageParams.limit"];
            };
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLogPage"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceMembers_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceMemberList"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceMembers_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceMemberCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceMember"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceMembers_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceMembers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceMemberUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceMember"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTags_list: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["PageParams.cursor"];
                limit?: components["parameters"]["PageParams.limit"];
            };
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPage"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTags_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTags_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                tagName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTags_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                tagName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskEffortLevels_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskEffortLevelList"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskEffortLevels_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskEffortLevelReplace"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskEffortLevelList"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskPriorityLevels_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPriorityLevelList"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskPriorityLevels_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPriorityLevelReplace"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPriorityLevelList"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskStatuses_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusList"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskStatuses_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusReplace"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusList"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTasks_list: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["PageParams.cursor"];
                limit?: components["parameters"]["PageParams.limit"];
            };
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPage"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTasks_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTasks_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTasks_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskActivity_list: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["PageParams.cursor"];
                limit?: components["parameters"]["PageParams.limit"];
            };
            header?: never;
            path: {
                spaceSlug: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLogPage"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskRelations_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRelationCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRelation"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SpaceTaskRelations_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceSlug: string;
                taskId: string;
                kind: components["schemas"]["TaskRelationKind"];
                relatedTaskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Users_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    UserActivity_list: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["PageParams.cursor"];
                limit?: components["parameters"]["PageParams.limit"];
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLogPage"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
