# yaml-language-server: $schema=https://www.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/sargunv/horologia/discussions
    about: Ask questions and get help in Discussions
