/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/app/auth/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Read public authentication configuration used by the web UI before login. */
    get: operations["WebAuth_config"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/app/auth/link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Confirm OIDC account linking using the existing account password.
     *
     *     This endpoint relies on the temporary `horologia_oidc_link` cookie issued
     *     during the OIDC callback. On success it creates the normal
     *     `horologia_session` cookie and clears the pending link cookie. This
     *     endpoint is only available when OIDC link consent is enabled.
     */
    post: operations["WebAuth_link"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/app/auth/link/pending": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Read the pending OIDC account-link request created during the OIDC callback.
     *
     *     This endpoint relies on the temporary `horologia_oidc_link` cookie and is
     *     only available when OIDC link consent is enabled.
     */
    get: operations["WebAuth_linkPending"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/app/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Log in with email and password.
     *
     *     Returns the authenticated user and sets the `horologia_session` cookie on
     *     success. This endpoint is only available when password auth is enabled.
     */
    post: operations["WebAuth_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/app/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Clear the current browser session. */
    post: operations["WebAuth_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Auth_listTokens"];
    put?: never;
    post: operations["Auth_createToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/tokens/{tokenId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["Auth_deleteToken"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Recipes_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipes/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Recipes_search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Spaces_list"];
    put?: never;
    post: operations["Spaces_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Spaces_read"];
    put?: never;
    post?: never;
    delete: operations["Spaces_delete"];
    options?: never;
    head?: never;
    patch: operations["Spaces_update"];
    trace?: never;
  };
  "/spaces/{spaceSlug}/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceActivity_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceMembers_list"];
    put?: never;
    post: operations["SpaceMembers_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/members/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["SpaceMembers_delete"];
    options?: never;
    head?: never;
    patch: operations["SpaceMembers_update"];
    trace?: never;
  };
  "/spaces/{spaceSlug}/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceRecipes_list"];
    put?: never;
    post: operations["SpaceRecipes_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/recipes/{recipeId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceRecipes_read"];
    put?: never;
    post?: never;
    delete: operations["SpaceRecipes_delete"];
    options?: never;
    head?: never;
    patch: operations["SpaceRecipes_update"];
    trace?: never;
  };
  "/spaces/{spaceSlug}/recipes/{recipeId}/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceRecipeActivity_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceTags_list"];
    put?: never;
    post: operations["SpaceTags_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/tags/{tagName}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["SpaceTags_delete"];
    options?: never;
    head?: never;
    patch: operations["SpaceTags_update"];
    trace?: never;
  };
  "/spaces/{spaceSlug}/task-effort-levels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceTaskEffortLevels_list"];
    put: operations["SpaceTaskEffortLevels_replace"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/task-priority-levels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceTaskPriorityLevels_list"];
    put: operations["SpaceTaskPriorityLevels_replace"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/task-statuses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceTaskStatuses_list"];
    put: operations["SpaceTaskStatuses_replace"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceTasks_list"];
    put?: never;
    post: operations["SpaceTasks_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/tasks/{taskId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceTasks_read"];
    put?: never;
    post?: never;
    delete: operations["SpaceTasks_delete"];
    options?: never;
    head?: never;
    patch: operations["SpaceTasks_update"];
    trace?: never;
  };
  "/spaces/{spaceSlug}/tasks/{taskId}/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SpaceTaskActivity_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/tasks/{taskId}/relations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["SpaceTaskRelations_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spaces/{spaceSlug}/tasks/{taskId}/relations/{kind}/{relatedTaskId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["SpaceTaskRelations_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tasks/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Tasks_search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Users_list"];
    put?: never;
    post: operations["Users_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Users_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["Users_get"];
    put?: never;
    post?: never;
    delete: operations["Users_delete"];
    options?: never;
    head?: never;
    patch: operations["Users_update"];
    trace?: never;
  };
  "/users/{userId}/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UserActivity_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{userId}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UserTasks_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    ActivityAction: "created" | "updated" | "deleted";
    ActivityDetail: {
      field: string;
      from: string | null;
      to: string | null;
    };
    /** @enum {string} */
    ActivityEntityType:
      | "task"
      | "recipe"
      | "space"
      | "member"
      | "tag"
      | "status"
      | "effort_level"
      | "priority_level"
      | "relation";
    ActivityLogEntry: {
      id: string;
      spaceSlug: string;
      actorId: string | null;
      tokenId: string | null;
      tokenName: string | null;
      entityType: components["schemas"]["ActivityEntityType"];
      entityId: string;
      action: components["schemas"]["ActivityAction"];
      details: components["schemas"]["ActivityDetail"][];
      /** Format: date-time */
      createdAt: string;
    };
    ActivityLogPage: {
      items: components["schemas"]["ActivityLogEntry"][];
      nextCursor: string | null;
    };
    ApiError: {
      code: string;
      message: string;
    };
    /** @enum {string} */
    AppearanceMode: "system" | "light" | "dark";
    AuthConfig: {
      oidc: components["schemas"]["AuthConfigOIDC"];
      password: components["schemas"]["AuthConfigPassword"];
    };
    AuthConfigOIDC: {
      enabled: boolean;
      label: string;
      autoRedirect: boolean;
    };
    AuthConfigPassword: {
      enabled: boolean;
    };
    AuthLinkPendingResponse: {
      email: string;
      name: string;
    };
    AuthLinkRequest: {
      password: string;
    };
    AuthLinkResponse: {
      redirectTo: string;
    };
    AuthLoginRequest: {
      email: string;
      password: string;
    };
    AuthLoginResponse: {
      user: components["schemas"]["User"];
    };
    AuthToken: {
      id: string;
      name: string;
      kind: components["schemas"]["AuthTokenKind"];
      /** Format: date-time */
      createdAt: string;
    };
    AuthTokenCreate: {
      name: string;
    };
    AuthTokenCreateResponse: {
      token: string;
      authToken: components["schemas"]["AuthToken"];
    };
    /** @enum {string} */
    AuthTokenKind: "session" | "api";
    AuthTokenList: {
      items: components["schemas"]["AuthToken"][];
    };
    Recipe: {
      id: string;
      spaceSlug: string;
      name: string;
      description: string;
      yield: components["schemas"]["RecipeYield"] | null;
      prepMinutes: number | null;
      cookMinutes: number | null;
      tags: string[];
      ingredientSections: components["schemas"]["RecipeIngredientSection"][];
      instructionSections: components["schemas"]["RecipeInstructionSection"][];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    RecipeCreate: {
      name: string;
      description?: string;
      yield?: components["schemas"]["RecipeYield"];
      /** Format: int32 */
      prepMinutes?: number;
      /** Format: int32 */
      cookMinutes?: number;
      tags?: string[];
      ingredientSections?: components["schemas"]["RecipeIngredientSectionInput"][];
      instructionSections?: components["schemas"]["RecipeInstructionSectionInput"][];
    };
    RecipeIngredient: {
      quantity: number | null;
      quantityMax: number | null;
      unit: string;
      item: string;
    };
    RecipeIngredientInput: {
      /** Format: double */
      quantity?: number;
      /** Format: double */
      quantityMax?: number;
      unit?: string;
      item: string;
    };
    RecipeIngredientSection: {
      title: string;
      ingredients: components["schemas"]["RecipeIngredient"][];
    };
    RecipeIngredientSectionInput: {
      title?: string;
      ingredients: components["schemas"]["RecipeIngredientInput"][];
    };
    RecipeInstructionSection: {
      title: string;
      steps: components["schemas"]["RecipeStep"][];
    };
    RecipeInstructionSectionInput: {
      title?: string;
      steps: components["schemas"]["RecipeStepInput"][];
    };
    RecipePage: {
      items: components["schemas"]["RecipeSummary"][];
      nextCursor: string | null;
    };
    RecipeSearchResultList: {
      items: components["schemas"]["RecipeSummary"][];
    };
    RecipeStep: {
      body: string;
    };
    RecipeStepInput: {
      body: string;
    };
    RecipeSummary: {
      id: string;
      spaceSlug: string;
      name: string;
      yield: components["schemas"]["RecipeYield"] | null;
      prepMinutes: number | null;
      cookMinutes: number | null;
      tags: string[];
      /** Format: date-time */
      updatedAt: string;
    };
    RecipeUpdate: {
      name?: string;
      description?: string;
      yield?: components["schemas"]["RecipeYield"] | null;
      prepMinutes?: number | null;
      cookMinutes?: number | null;
      tags?: string[];
      ingredientSections?: components["schemas"]["RecipeIngredientSectionInput"][];
      instructionSections?: components["schemas"]["RecipeInstructionSectionInput"][];
    };
    RecipeYield: {
      /** Format: double */
      amount: number;
      unit: string;
    };
    Space: {
      slug: string;
      name: string;
      description: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SpaceCreate: {
      slug: string;
      name: string;
      description?: string;
    };
    SpaceList: {
      items: components["schemas"]["Space"][];
    };
    SpaceMember: {
      userId: string;
      userName: string;
      userEmail: string;
      role: components["schemas"]["SpaceRole"];
      /** Format: date-time */
      createdAt: string;
    };
    SpaceMemberCreate: {
      userId: string;
      role: components["schemas"]["SpaceRole"];
    };
    SpaceMemberList: {
      items: components["schemas"]["SpaceMember"][];
    };
    SpaceMemberUpdate: {
      role: components["schemas"]["SpaceRole"];
    };
    /** @enum {string} */
    SpaceRole: "admin" | "member" | "viewer";
    SpaceUpdate: {
      slug?: string;
      name?: string;
      description?: string;
    };
    Tag: {
      name: string;
      /** Format: date-time */
      createdAt: string;
    };
    TagCreate: {
      name: string;
    };
    TagList: {
      items: components["schemas"]["Tag"][];
    };
    TagUpdate: {
      name: string;
    };
    Task: {
      id: string;
      spaceSlug: string;
      title: string;
      description: string;
      status: string;
      effort: string | null;
      priority: string | null;
      recurrenceType: components["schemas"]["TaskRecurrenceType"];
      recurrenceRule: string | null;
      lastCompletedAt: string | null;
      assigneeIds: string[];
      rotationPool: string[];
      tags: string[];
      relations: components["schemas"]["TaskRelation"][];
      due: components["schemas"]["TaskDue"] | null;
      overdueActionRule: components["schemas"]["TaskOverdueActionRule"] | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    TaskCreate: {
      /** @description Task title (1–500 chars). */
      title: string;
      /** @description Task description (max 10000 chars). */
      description?: string;
      /** @description Initial status name. Defaults to the space's first status. */
      status?: string;
      /** @description Effort level name. */
      effort?: string;
      /** @description Priority level name. */
      priority?: string;
      /** @description Recurrence type (e.g. one_off, completion_based, fixed_accumulating). */
      recurrenceType?: components["schemas"]["TaskRecurrenceType"];
      /** @description Recurrence rule (RRULE string, max 500 chars). */
      recurrenceRule?: string;
      assigneeIds?: string[];
      rotationPool?: string[];
      tags?: string[];
      due?: components["schemas"]["TaskDue"] | null;
      overdueActionRule?: components["schemas"]["TaskOverdueActionRule"] | null;
    };
    TaskDue: {
      /** Format: date */
      at: string;
      timezone: string;
    };
    TaskEffortLevel: {
      name: string;
      /** Format: int64 */
      position: number;
      /** @description Lucide icon name in kebab-case (e.g. "gauge", "flame"). Empty string if no icon is set. */
      icon: string;
    };
    TaskEffortLevelInput: {
      name: string;
      /** @description Lucide icon name in kebab-case (e.g. "gauge", "flame"). Omit or set to empty string to clear. */
      icon?: string;
    };
    TaskEffortLevelList: {
      items: components["schemas"]["TaskEffortLevel"][];
    };
    TaskEffortLevelReplace: {
      items: components["schemas"]["TaskEffortLevelInput"][];
    };
    /** @enum {string} */
    TaskOverdueAction: "advance_recurrence" | "set_status" | "clear_due_date";
    TaskOverdueActionRule: {
      /**
       * @description Grace period in days after the due date before the action fires.
       *           null means act immediately when the task becomes overdue.
       */
      after: number | null;
      action: components["schemas"]["TaskOverdueAction"];
      /** @description Required when action is set_status; the status name to transition to. */
      status?: string;
    };
    TaskPage: {
      items: components["schemas"]["Task"][];
      nextCursor: string | null;
    };
    TaskPriorityLevel: {
      name: string;
      /** Format: int64 */
      position: number;
      /** @description Lucide icon name in kebab-case (e.g. "signal-high", "flag"). Empty string if no icon is set. */
      icon: string;
    };
    TaskPriorityLevelInput: {
      name: string;
      /** @description Lucide icon name in kebab-case (e.g. "signal-high", "flag"). Omit or set to empty string to clear. */
      icon?: string;
    };
    TaskPriorityLevelList: {
      items: components["schemas"]["TaskPriorityLevel"][];
    };
    TaskPriorityLevelReplace: {
      items: components["schemas"]["TaskPriorityLevelInput"][];
    };
    /** @enum {string} */
    TaskRecurrenceType:
      | "one_off"
      | "completion_based"
      | "fixed_non_accumulating"
      | "fixed_accumulating"
      | "on_dependency";
    TaskRelation: {
      kind: components["schemas"]["TaskRelationKind"];
      relatedTaskId: string;
      /** Format: date-time */
      createdAt: string;
    };
    TaskRelationCreate: {
      /** @description Relation kind (e.g. parent_of, child_of, blocks, blocked_by, relates_to, duplicates, triggers, triggered_by). */
      kind: components["schemas"]["TaskRelationKind"];
      /** @description Task ID of the related task. */
      relatedTaskId: string;
    };
    /** @enum {string} */
    TaskRelationKind:
      | "parent_of"
      | "child_of"
      | "blocks"
      | "blocked_by"
      | "relates_to"
      | "duplicates"
      | "triggers"
      | "triggered_by"
      | "spawns"
      | "spawned_by";
    TaskSearchResult: {
      id: string;
      spaceSlug: string;
      title: string;
      status: string;
    };
    TaskSearchResultList: {
      items: components["schemas"]["TaskSearchResult"][];
    };
    TaskStatus: {
      name: string;
      category: components["schemas"]["TaskStatusCategory"];
      /** Format: int64 */
      position: number;
      /** @description Lucide icon name in kebab-case (e.g. "circle-check", "loader"). Empty string if no icon is set. */
      icon: string;
    };
    /** @enum {string} */
    TaskStatusCategory: "initial" | "intermediate" | "completion";
    TaskStatusInput: {
      name: string;
      category: components["schemas"]["TaskStatusCategory"];
      /** @description Lucide icon name in kebab-case (e.g. "circle-check", "loader"). Omit or set to empty string to clear. */
      icon?: string;
    };
    TaskStatusList: {
      items: components["schemas"]["TaskStatus"][];
    };
    TaskStatusReplace: {
      items: components["schemas"]["TaskStatusInput"][];
    };
    TaskUpdate: {
      /** @description New title. */
      title?: string;
      /** @description New description. */
      description?: string;
      /** @description New status name. */
      status?: string;
      /** @description New effort level name. */
      effort?: string | null;
      /** @description New priority level name. */
      priority?: string | null;
      /** @description New recurrence type. */
      recurrenceType?: components["schemas"]["TaskRecurrenceType"];
      /** @description New recurrence rule (RRULE string, max 500 chars). */
      recurrenceRule?: string | null;
      assigneeIds?: string[];
      rotationPool?: string[];
      tags?: string[];
      due?: components["schemas"]["TaskDue"] | null;
      overdueActionRule?: components["schemas"]["TaskOverdueActionRule"] | null;
    };
    User: {
      id: string;
      email: string;
      name: string;
      isOwner: boolean;
      hasPassword: boolean;
      appearanceMode: components["schemas"]["AppearanceMode"];
      appearanceLightTheme: string;
      appearanceDarkTheme: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserCreate: {
      name: string;
      email: string;
      isOwner?: boolean;
      password?: string;
    };
    UserList: {
      items: components["schemas"]["User"][];
    };
    UserUpdate: {
      name?: string;
      email?: string;
      isOwner?: boolean;
      appearanceMode?: components["schemas"]["AppearanceMode"];
      appearanceLightTheme?: string;
      appearanceDarkTheme?: string;
      setPassword?: string;
      clearPassword?: boolean;
    };
  };
  responses: never;
  parameters: {
    /** @description Pagination cursor from a previous response. */
    "PageParams.cursor": string;
    /** @description Maximum number of items to return (1–100). */
    "PageParams.limit": number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  WebAuth_config: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthConfig"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  WebAuth_link: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthLinkRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          "Set-Cookie": string[];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthLinkResponse"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  WebAuth_linkPending: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthLinkPendingResponse"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  WebAuth_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthLoginRequest"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          "Set-Cookie": string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthLoginResponse"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  WebAuth_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          "Set-Cookie": string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Auth_listTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthTokenList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Auth_createToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthTokenCreate"];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthTokenCreateResponse"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Auth_deleteToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Token ID. */
        tokenId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Recipes_list: {
    parameters: {
      query?: {
        /** @description Pagination cursor from a previous response. */
        cursor?: components["parameters"]["PageParams.cursor"];
        /** @description Maximum number of items to return (1–100). */
        limit?: components["parameters"]["PageParams.limit"];
        spaceSlug?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipePage"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Recipes_search: {
    parameters: {
      query: {
        q: string;
        spaceSlug?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeSearchResultList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Spaces_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpaceList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Spaces_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpaceCreate"];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Space"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Spaces_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Space"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Spaces_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Spaces_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpaceUpdate"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Space"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceActivity_list: {
    parameters: {
      query?: {
        /** @description Pagination cursor from a previous response. */
        cursor?: components["parameters"]["PageParams.cursor"];
        /** @description Maximum number of items to return (1–100). */
        limit?: components["parameters"]["PageParams.limit"];
      };
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityLogPage"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceMembers_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpaceMemberList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceMembers_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpaceMemberCreate"];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpaceMember"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceMembers_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description User ID of the member. */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceMembers_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description User ID of the member. */
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpaceMemberUpdate"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpaceMember"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceRecipes_list: {
    parameters: {
      query?: {
        /** @description Pagination cursor from a previous response. */
        cursor?: components["parameters"]["PageParams.cursor"];
        /** @description Maximum number of items to return (1–100). */
        limit?: components["parameters"]["PageParams.limit"];
      };
      header?: never;
      path: {
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipePage"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceRecipes_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeCreate"];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipe"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceRecipes_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        spaceSlug: string;
        recipeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipe"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceRecipes_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        spaceSlug: string;
        recipeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceRecipes_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        spaceSlug: string;
        recipeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeUpdate"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipe"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceRecipeActivity_list: {
    parameters: {
      query?: {
        /** @description Pagination cursor from a previous response. */
        cursor?: components["parameters"]["PageParams.cursor"];
        /** @description Maximum number of items to return (1–100). */
        limit?: components["parameters"]["PageParams.limit"];
      };
      header?: never;
      path: {
        spaceSlug: string;
        recipeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityLogPage"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTags_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TagList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTags_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagCreate"];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Tag"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTags_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description Tag name to delete. */
        tagName: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTags_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description Current tag name. */
        tagName: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagUpdate"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Tag"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskEffortLevels_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskEffortLevelList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskEffortLevels_replace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskEffortLevelReplace"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskEffortLevelList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskPriorityLevels_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPriorityLevelList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskPriorityLevels_replace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskPriorityLevelReplace"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPriorityLevelList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskStatuses_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskStatusList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskStatuses_replace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskStatusReplace"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskStatusList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTasks_list: {
    parameters: {
      query?: {
        /** @description Pagination cursor from a previous response. */
        cursor?: components["parameters"]["PageParams.cursor"];
        /** @description Maximum number of items to return (1–100). */
        limit?: components["parameters"]["PageParams.limit"];
      };
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPage"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTasks_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreate"];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTasks_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description Task ID. */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTasks_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description Task ID. */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTasks_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description Task ID. */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskUpdate"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskActivity_list: {
    parameters: {
      query?: {
        /** @description Pagination cursor from a previous response. */
        cursor?: components["parameters"]["PageParams.cursor"];
        /** @description Maximum number of items to return (1–100). */
        limit?: components["parameters"]["PageParams.limit"];
      };
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description Task ID. */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityLogPage"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskRelations_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description Task ID of the source task. */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskRelationCreate"];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskRelation"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  SpaceTaskRelations_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug of the space. */
        spaceSlug: string;
        /** @description Task ID of the source task. */
        taskId: string;
        /** @description Relation kind. */
        kind: components["schemas"]["TaskRelationKind"];
        /** @description Task ID of the related task. */
        relatedTaskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Tasks_search: {
    parameters: {
      query: {
        /** @description Search query. */
        q: string;
        /** @description Optional space slug to restrict results to a single space. */
        spaceSlug?: string;
        /** @description Optional task ID to exclude from results. */
        excludeTaskId?: string;
        /** @description Maximum number of items to return (1–100). */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskSearchResultList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Users_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserList"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Users_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Users_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Users_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID. */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Users_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID. */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description There is no content to send for this request, but the headers may be useful. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  Users_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID. */
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  UserActivity_list: {
    parameters: {
      query?: {
        /** @description Pagination cursor from a previous response. */
        cursor?: components["parameters"]["PageParams.cursor"];
        /** @description Maximum number of items to return (1–100). */
        limit?: components["parameters"]["PageParams.limit"];
      };
      header?: never;
      path: {
        /** @description User ID. */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityLogPage"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  UserTasks_list: {
    parameters: {
      query?: {
        /** @description Pagination cursor from a previous response. */
        cursor?: components["parameters"]["PageParams.cursor"];
        /** @description Maximum number of items to return (1–100). */
        limit?: components["parameters"]["PageParams.limit"];
      };
      header?: never;
      path: {
        /** @description User ID. */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPage"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
}
