/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSpacesIndexRouteImport } from './routes/_authenticated/spaces/index'
import { Route as AuthenticatedSpacesNewRouteImport } from './routes/_authenticated/spaces/new'
import { Route as AuthenticatedSpacesSpaceSlugRouteRouteImport } from './routes/_authenticated/spaces/$spaceSlug/route'
import { Route as AuthenticatedSpacesSpaceSlugIndexRouteImport } from './routes/_authenticated/spaces/$spaceSlug/index'
import { Route as AuthenticatedSpacesSpaceSlugSettingsRouteImport } from './routes/_authenticated/spaces/$spaceSlug/settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpacesIndexRoute =
  AuthenticatedSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpacesNewRoute = AuthenticatedSpacesNewRouteImport.update({
  id: '/spaces/new',
  path: '/spaces/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpacesSpaceSlugRouteRoute =
  AuthenticatedSpacesSpaceSlugRouteRouteImport.update({
    id: '/spaces/$spaceSlug',
    path: '/spaces/$spaceSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpacesSpaceSlugIndexRoute =
  AuthenticatedSpacesSpaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSpacesSpaceSlugRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceSlugSettingsRoute =
  AuthenticatedSpacesSpaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSpacesSpaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spaces/$spaceSlug': typeof AuthenticatedSpacesSpaceSlugRouteRouteWithChildren
  '/spaces/new': typeof AuthenticatedSpacesNewRoute
  '/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/spaces/$spaceSlug/settings': typeof AuthenticatedSpacesSpaceSlugSettingsRoute
  '/spaces/$spaceSlug/': typeof AuthenticatedSpacesSpaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/spaces/new': typeof AuthenticatedSpacesNewRoute
  '/spaces': typeof AuthenticatedSpacesIndexRoute
  '/spaces/$spaceSlug/settings': typeof AuthenticatedSpacesSpaceSlugSettingsRoute
  '/spaces/$spaceSlug': typeof AuthenticatedSpacesSpaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/spaces/$spaceSlug': typeof AuthenticatedSpacesSpaceSlugRouteRouteWithChildren
  '/_authenticated/spaces/new': typeof AuthenticatedSpacesNewRoute
  '/_authenticated/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/_authenticated/spaces/$spaceSlug/settings': typeof AuthenticatedSpacesSpaceSlugSettingsRoute
  '/_authenticated/spaces/$spaceSlug/': typeof AuthenticatedSpacesSpaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/settings'
    | '/spaces/$spaceSlug'
    | '/spaces/new'
    | '/spaces/'
    | '/spaces/$spaceSlug/settings'
    | '/spaces/$spaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/settings'
    | '/'
    | '/spaces/new'
    | '/spaces'
    | '/spaces/$spaceSlug/settings'
    | '/spaces/$spaceSlug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/spaces/$spaceSlug'
    | '/_authenticated/spaces/new'
    | '/_authenticated/spaces/'
    | '/_authenticated/spaces/$spaceSlug/settings'
    | '/_authenticated/spaces/$spaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/': {
      id: '/_authenticated/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthenticatedSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/new': {
      id: '/_authenticated/spaces/new'
      path: '/spaces/new'
      fullPath: '/spaces/new'
      preLoaderRoute: typeof AuthenticatedSpacesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/$spaceSlug': {
      id: '/_authenticated/spaces/$spaceSlug'
      path: '/spaces/$spaceSlug'
      fullPath: '/spaces/$spaceSlug'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/$spaceSlug/': {
      id: '/_authenticated/spaces/$spaceSlug/'
      path: '/'
      fullPath: '/spaces/$spaceSlug/'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceSlugRouteRoute
    }
    '/_authenticated/spaces/$spaceSlug/settings': {
      id: '/_authenticated/spaces/$spaceSlug/settings'
      path: '/settings'
      fullPath: '/spaces/$spaceSlug/settings'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceSlugRouteRoute
    }
  }
}

interface AuthenticatedSpacesSpaceSlugRouteRouteChildren {
  AuthenticatedSpacesSpaceSlugSettingsRoute: typeof AuthenticatedSpacesSpaceSlugSettingsRoute
  AuthenticatedSpacesSpaceSlugIndexRoute: typeof AuthenticatedSpacesSpaceSlugIndexRoute
}

const AuthenticatedSpacesSpaceSlugRouteRouteChildren: AuthenticatedSpacesSpaceSlugRouteRouteChildren =
  {
    AuthenticatedSpacesSpaceSlugSettingsRoute:
      AuthenticatedSpacesSpaceSlugSettingsRoute,
    AuthenticatedSpacesSpaceSlugIndexRoute:
      AuthenticatedSpacesSpaceSlugIndexRoute,
  }

const AuthenticatedSpacesSpaceSlugRouteRouteWithChildren =
  AuthenticatedSpacesSpaceSlugRouteRoute._addFileChildren(
    AuthenticatedSpacesSpaceSlugRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSpacesSpaceSlugRouteRoute: typeof AuthenticatedSpacesSpaceSlugRouteRouteWithChildren
  AuthenticatedSpacesNewRoute: typeof AuthenticatedSpacesNewRoute
  AuthenticatedSpacesIndexRoute: typeof AuthenticatedSpacesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSpacesSpaceSlugRouteRoute:
    AuthenticatedSpacesSpaceSlugRouteRouteWithChildren,
  AuthenticatedSpacesNewRoute: AuthenticatedSpacesNewRoute,
  AuthenticatedSpacesIndexRoute: AuthenticatedSpacesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
