/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as LinkAccountRouteImport } from './routes/link-account.tsx'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated.tsx'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index.tsx'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings.tsx'
import { Route as AuthenticatedPlaygroundRouteImport } from './routes/_authenticated/playground.tsx'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity.tsx'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route.tsx'
import { Route as AuthenticatedSpacesIndexRouteImport } from './routes/_authenticated/spaces/index.tsx'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index.tsx'
import { Route as AuthenticatedSpacesNewRouteImport } from './routes/_authenticated/spaces/new.tsx'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users.tsx'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin/about.tsx'
import { Route as AuthenticatedSpacesSpaceSlugRouteRouteImport } from './routes/_authenticated/spaces/$spaceSlug/route.tsx'
import { Route as AuthenticatedSpacesSpaceSlugIndexRouteImport } from './routes/_authenticated/spaces/$spaceSlug/index.tsx'
import { Route as AuthenticatedSpacesSpaceSlugSettingsRouteImport } from './routes/_authenticated/spaces/$spaceSlug/settings.tsx'
import { Route as AuthenticatedSpacesSpaceSlugActivityRouteImport } from './routes/_authenticated/spaces/$spaceSlug/activity.tsx'
import { Route as AuthenticatedSpacesSpaceSlugTasksNewRouteImport } from './routes/_authenticated/spaces/$spaceSlug/tasks/new.tsx'
import { Route as AuthenticatedSpacesSpaceSlugTasksTaskIdRouteImport } from './routes/_authenticated/spaces/$spaceSlug/tasks/$taskId.tsx'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkAccountRoute = LinkAccountRouteImport.update({
  id: '/link-account',
  path: '/link-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlaygroundRoute = AuthenticatedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpacesIndexRoute =
  AuthenticatedSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedSpacesNewRoute = AuthenticatedSpacesNewRouteImport.update({
  id: '/spaces/new',
  path: '/spaces/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedSpacesSpaceSlugRouteRoute =
  AuthenticatedSpacesSpaceSlugRouteRouteImport.update({
    id: '/spaces/$spaceSlug',
    path: '/spaces/$spaceSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpacesSpaceSlugIndexRoute =
  AuthenticatedSpacesSpaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSpacesSpaceSlugRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceSlugSettingsRoute =
  AuthenticatedSpacesSpaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSpacesSpaceSlugRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceSlugActivityRoute =
  AuthenticatedSpacesSpaceSlugActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedSpacesSpaceSlugRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceSlugTasksNewRoute =
  AuthenticatedSpacesSpaceSlugTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => AuthenticatedSpacesSpaceSlugRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceSlugTasksTaskIdRoute =
  AuthenticatedSpacesSpaceSlugTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedSpacesSpaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/link-account': typeof LinkAccountRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spaces/$spaceSlug': typeof AuthenticatedSpacesSpaceSlugRouteRouteWithChildren
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/spaces/new': typeof AuthenticatedSpacesNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/spaces/$spaceSlug/activity': typeof AuthenticatedSpacesSpaceSlugActivityRoute
  '/spaces/$spaceSlug/settings': typeof AuthenticatedSpacesSpaceSlugSettingsRoute
  '/spaces/$spaceSlug/': typeof AuthenticatedSpacesSpaceSlugIndexRoute
  '/spaces/$spaceSlug/tasks/$taskId': typeof AuthenticatedSpacesSpaceSlugTasksTaskIdRoute
  '/spaces/$spaceSlug/tasks/new': typeof AuthenticatedSpacesSpaceSlugTasksNewRoute
}
export interface FileRoutesByTo {
  '/link-account': typeof LinkAccountRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/spaces/new': typeof AuthenticatedSpacesNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/spaces': typeof AuthenticatedSpacesIndexRoute
  '/spaces/$spaceSlug/activity': typeof AuthenticatedSpacesSpaceSlugActivityRoute
  '/spaces/$spaceSlug/settings': typeof AuthenticatedSpacesSpaceSlugSettingsRoute
  '/spaces/$spaceSlug': typeof AuthenticatedSpacesSpaceSlugIndexRoute
  '/spaces/$spaceSlug/tasks/$taskId': typeof AuthenticatedSpacesSpaceSlugTasksTaskIdRoute
  '/spaces/$spaceSlug/tasks/new': typeof AuthenticatedSpacesSpaceSlugTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/link-account': typeof LinkAccountRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/spaces/$spaceSlug': typeof AuthenticatedSpacesSpaceSlugRouteRouteWithChildren
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/spaces/new': typeof AuthenticatedSpacesNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/_authenticated/spaces/$spaceSlug/activity': typeof AuthenticatedSpacesSpaceSlugActivityRoute
  '/_authenticated/spaces/$spaceSlug/settings': typeof AuthenticatedSpacesSpaceSlugSettingsRoute
  '/_authenticated/spaces/$spaceSlug/': typeof AuthenticatedSpacesSpaceSlugIndexRoute
  '/_authenticated/spaces/$spaceSlug/tasks/$taskId': typeof AuthenticatedSpacesSpaceSlugTasksTaskIdRoute
  '/_authenticated/spaces/$spaceSlug/tasks/new': typeof AuthenticatedSpacesSpaceSlugTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/link-account'
    | '/login'
    | '/admin'
    | '/activity'
    | '/playground'
    | '/settings'
    | '/spaces/$spaceSlug'
    | '/admin/about'
    | '/admin/users'
    | '/spaces/new'
    | '/admin/'
    | '/spaces/'
    | '/spaces/$spaceSlug/activity'
    | '/spaces/$spaceSlug/settings'
    | '/spaces/$spaceSlug/'
    | '/spaces/$spaceSlug/tasks/$taskId'
    | '/spaces/$spaceSlug/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/link-account'
    | '/login'
    | '/activity'
    | '/playground'
    | '/settings'
    | '/'
    | '/admin/about'
    | '/admin/users'
    | '/spaces/new'
    | '/admin'
    | '/spaces'
    | '/spaces/$spaceSlug/activity'
    | '/spaces/$spaceSlug/settings'
    | '/spaces/$spaceSlug'
    | '/spaces/$spaceSlug/tasks/$taskId'
    | '/spaces/$spaceSlug/tasks/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/link-account'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/activity'
    | '/_authenticated/playground'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/spaces/$spaceSlug'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/users'
    | '/_authenticated/spaces/new'
    | '/_authenticated/admin/'
    | '/_authenticated/spaces/'
    | '/_authenticated/spaces/$spaceSlug/activity'
    | '/_authenticated/spaces/$spaceSlug/settings'
    | '/_authenticated/spaces/$spaceSlug/'
    | '/_authenticated/spaces/$spaceSlug/tasks/$taskId'
    | '/_authenticated/spaces/$spaceSlug/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LinkAccountRoute: typeof LinkAccountRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-account': {
      id: '/link-account'
      path: '/link-account'
      fullPath: '/link-account'
      preLoaderRoute: typeof LinkAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playground': {
      id: '/_authenticated/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/': {
      id: '/_authenticated/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthenticatedSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/spaces/new': {
      id: '/_authenticated/spaces/new'
      path: '/spaces/new'
      fullPath: '/spaces/new'
      preLoaderRoute: typeof AuthenticatedSpacesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/spaces/$spaceSlug': {
      id: '/_authenticated/spaces/$spaceSlug'
      path: '/spaces/$spaceSlug'
      fullPath: '/spaces/$spaceSlug'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/$spaceSlug/': {
      id: '/_authenticated/spaces/$spaceSlug/'
      path: '/'
      fullPath: '/spaces/$spaceSlug/'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceSlugRouteRoute
    }
    '/_authenticated/spaces/$spaceSlug/settings': {
      id: '/_authenticated/spaces/$spaceSlug/settings'
      path: '/settings'
      fullPath: '/spaces/$spaceSlug/settings'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceSlugRouteRoute
    }
    '/_authenticated/spaces/$spaceSlug/activity': {
      id: '/_authenticated/spaces/$spaceSlug/activity'
      path: '/activity'
      fullPath: '/spaces/$spaceSlug/activity'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugActivityRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceSlugRouteRoute
    }
    '/_authenticated/spaces/$spaceSlug/tasks/new': {
      id: '/_authenticated/spaces/$spaceSlug/tasks/new'
      path: '/tasks/new'
      fullPath: '/spaces/$spaceSlug/tasks/new'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugTasksNewRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceSlugRouteRoute
    }
    '/_authenticated/spaces/$spaceSlug/tasks/$taskId': {
      id: '/_authenticated/spaces/$spaceSlug/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/spaces/$spaceSlug/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceSlugTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceSlugRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSpacesSpaceSlugRouteRouteChildren {
  AuthenticatedSpacesSpaceSlugActivityRoute: typeof AuthenticatedSpacesSpaceSlugActivityRoute
  AuthenticatedSpacesSpaceSlugSettingsRoute: typeof AuthenticatedSpacesSpaceSlugSettingsRoute
  AuthenticatedSpacesSpaceSlugIndexRoute: typeof AuthenticatedSpacesSpaceSlugIndexRoute
  AuthenticatedSpacesSpaceSlugTasksTaskIdRoute: typeof AuthenticatedSpacesSpaceSlugTasksTaskIdRoute
  AuthenticatedSpacesSpaceSlugTasksNewRoute: typeof AuthenticatedSpacesSpaceSlugTasksNewRoute
}

const AuthenticatedSpacesSpaceSlugRouteRouteChildren: AuthenticatedSpacesSpaceSlugRouteRouteChildren =
  {
    AuthenticatedSpacesSpaceSlugActivityRoute:
      AuthenticatedSpacesSpaceSlugActivityRoute,
    AuthenticatedSpacesSpaceSlugSettingsRoute:
      AuthenticatedSpacesSpaceSlugSettingsRoute,
    AuthenticatedSpacesSpaceSlugIndexRoute:
      AuthenticatedSpacesSpaceSlugIndexRoute,
    AuthenticatedSpacesSpaceSlugTasksTaskIdRoute:
      AuthenticatedSpacesSpaceSlugTasksTaskIdRoute,
    AuthenticatedSpacesSpaceSlugTasksNewRoute:
      AuthenticatedSpacesSpaceSlugTasksNewRoute,
  }

const AuthenticatedSpacesSpaceSlugRouteRouteWithChildren =
  AuthenticatedSpacesSpaceSlugRouteRoute._addFileChildren(
    AuthenticatedSpacesSpaceSlugRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedPlaygroundRoute: typeof AuthenticatedPlaygroundRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSpacesSpaceSlugRouteRoute: typeof AuthenticatedSpacesSpaceSlugRouteRouteWithChildren
  AuthenticatedSpacesNewRoute: typeof AuthenticatedSpacesNewRoute
  AuthenticatedSpacesIndexRoute: typeof AuthenticatedSpacesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedPlaygroundRoute: AuthenticatedPlaygroundRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSpacesSpaceSlugRouteRoute:
    AuthenticatedSpacesSpaceSlugRouteRouteWithChildren,
  AuthenticatedSpacesNewRoute: AuthenticatedSpacesNewRoute,
  AuthenticatedSpacesIndexRoute: AuthenticatedSpacesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LinkAccountRoute: LinkAccountRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
