emit:
  - "@typespec/openapi3"
  - "@tend/typespec-mcp-go"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.1.0
  "@tend/typespec-mcp-go":
    emitter-output-dir: "{project-root}/../server/internal/mcp/gen"
    ogenImportPath: "github.com/sargunv/tend/api/gen"
